// export enum UrlTypeEnum {
//     FOR_FORM_W9 = "FOR_FORM_W9",
//     FOR_TAX_EXEMPTION_CERTIFICATE = "FOR_TAX_EXEMPTION_CERTIFICATE",
//     FOR_DATA_SHEET = "FOR_DATA_SHEET",
//     FOR_PRODUCT_IMAGE = "FOR_PRODUCT_IMAGE",
//     FOR_PRODUCT_PRIMARY_AVATAR_IMAGE = "FOR_PRODUCT_PRIMARY_AVATAR_IMAGE",
//     FOR_USER_AVATAR = "FOR_USER_AVATAR",
//     FOR_COMPANY_AVATAR = "FOR_COMPANY_AVATAR",
//     FOR_REPORT = "FOR_REPORT"
// }