name: Deploy NestJS to EC2 (Production)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Starting Production Deployment..."

            PROJECT_DIR="/home/ec2-user/recruiser/recruiser_backend"
            SERVICE_NAME="interview_api"

            sudo mkdir -p "$PROJECT_DIR"
            sudo chown ec2-user:ec2-user "$PROJECT_DIR"

            if [ ! -d "$PROJECT_DIR" ]; then
              git clone git@github.com:BrainBoltConsulting/Recruiser_backend.git "$PROJECT_DIR"
            else
              cd "$PROJECT_DIR"
              git pull origin production || { echo 'Git pull failed. Exiting...'; exit 1; }
            fi

            cd "$PROJECT_DIR"

            # Copy production .env file
            if [ -f "../.temp.env" ]; then
              cp ../.temp.env .env
            else
              echo "ERROR: .temp.env file is missing! Exiting..."
              exit 1
            fi

            echo "Environment variables for production set."

            npm install --force || { echo 'Failed to install npm dependencies. Exiting...'; exit 1; }

            npm run build:prod || { echo 'Failed to build the NestJS application. Exiting...'; exit 1; }

            echo "Proceeding with production deployment..."

            # Stop the existing service if it's running
            if sudo systemctl is-active --quiet $SERVICE_NAME; then
              echo "Stopping existing $SERVICE_NAME service..."
              sudo systemctl stop $SERVICE_NAME || { echo "Failed to stop service. Exiting..."; exit 1; }
              echo "Service stopped successfully."
            else
              echo "No existing service found. Proceeding with deployment."
            fi

            # Load environment variables
            export $(grep -v '^#' .env | xargs)

            # Start the service using systemctl
            echo "Starting $SERVICE_NAME service..."
            sudo systemctl start $SERVICE_NAME || { echo "Failed to start service. Exiting..."; exit 1; }

            # Wait a moment for the service to start
            sleep 5

            # Check if the service is running
            if sudo systemctl is-active --quiet $SERVICE_NAME; then
              echo "Service started successfully!"
              
              # Show service status
              sudo systemctl status $SERVICE_NAME --no-pager -l
              
              echo "Production Deployment Complete!"
            else
              echo "ERROR: Service failed to start!"
              sudo systemctl status $SERVICE_NAME --no-pager -l
              exit 1
            fi
